import { UnitType } from '../../constants';
import type { UnlockDefinition } from './CampaignTypes';

export const UNLOCK_DEFINITIONS: UnlockDefinition[] = [
  {
    id: 'gong_archers',
    name: 'Gong Archers', chineseName: '弓兵',
    cost: 20,
    description: 'Archers available for recruitment',
    effect: { type: 'unit_unlock', unitType: UnitType.GONG_ARCHERS },
    prerequisiteIds: [],
  },
  {
    id: 'light_cavalry',
    name: 'Light Cavalry', chineseName: '轻骑',
    cost: 30,
    description: 'Light cavalry available for recruitment',
    effect: { type: 'unit_unlock', unitType: UnitType.LIGHT_CAVALRY },
    prerequisiteIds: [],
  },
  {
    id: 'heavy_cavalry',
    name: 'Heavy Cavalry', chineseName: '重骑',
    cost: 50,
    description: 'Heavy cavalry available for recruitment',
    effect: { type: 'unit_unlock', unitType: UnitType.HEAVY_CAVALRY },
    prerequisiteIds: ['light_cavalry'],
  },
  {
    id: 'horse_archers',
    name: 'Horse Archers', chineseName: '骑射',
    cost: 40,
    description: 'Horse archers available for recruitment',
    effect: { type: 'unit_unlock', unitType: UnitType.HORSE_ARCHERS },
    prerequisiteIds: ['light_cavalry'],
  },
  {
    id: 'siege_engineers',
    name: 'Siege Engineers', chineseName: '攻城兵',
    cost: 60,
    description: 'Siege engineers available for recruitment',
    effect: { type: 'unit_unlock', unitType: UnitType.SIEGE_ENGINEERS },
    prerequisiteIds: [],
  },
  {
    id: 'elite_guard',
    name: 'Elite Guard', chineseName: '亲卫',
    cost: 80,
    description: 'Elite guard available for recruitment',
    effect: { type: 'unit_unlock', unitType: UnitType.ELITE_GUARD },
    prerequisiteIds: [],
  },
  {
    id: 'naval_meng_chong',
    name: 'Naval Meng Chong', chineseName: '蒙冲',
    cost: 35,
    description: 'Assault boats available for recruitment',
    effect: { type: 'unit_unlock', unitType: UnitType.MENG_CHONG },
    prerequisiteIds: [],
  },
  {
    id: 'naval_lou_chuan',
    name: 'Naval Lou Chuan', chineseName: '楼船',
    cost: 55,
    description: 'Tower ships available for recruitment',
    effect: { type: 'unit_unlock', unitType: UnitType.LOU_CHUAN },
    prerequisiteIds: ['naval_meng_chong'],
  },
  {
    id: 'naval_fire_ships',
    name: 'Naval Fire Ships', chineseName: '火船',
    cost: 45,
    description: 'Fire ships available for recruitment',
    effect: { type: 'unit_unlock', unitType: UnitType.FIRE_SHIPS },
    prerequisiteIds: ['naval_meng_chong'],
  },
  {
    id: 'war_college',
    name: 'War College', chineseName: '武学',
    cost: 100,
    description: 'Starting squads begin at exp 20',
    effect: { type: 'starting_bonus', bonus: 'starting_exp', value: 20 },
    prerequisiteIds: [],
  },
  {
    id: 'grand_strategist',
    name: 'Grand Strategist', chineseName: '大战略家',
    cost: 150,
    description: '+20% starting army size',
    effect: { type: 'starting_bonus', bonus: 'army_size_mult', value: 1.2 },
    prerequisiteIds: ['war_college'],
  },
  {
    id: 'iron_discipline',
    name: 'Iron Discipline', chineseName: '铁律',
    cost: 70,
    description: 'Rout threshold -5 for all units',
    effect: { type: 'stat_bonus', stat: 'rout_threshold', value: -5 },
    prerequisiteIds: [],
  },
  {
    id: 'swift_messengers',
    name: 'Swift Messengers', chineseName: '急使',
    cost: 60,
    description: 'Command delay -25%',
    effect: { type: 'stat_bonus', stat: 'command_delay', value: 0.75 },
    prerequisiteIds: [],
  },
  {
    id: 'dragon_banner',
    name: 'Dragon Banner', chineseName: '龙旗',
    cost: 90,
    description: 'General command radius +30%',
    effect: { type: 'stat_bonus', stat: 'command_radius', value: 1.3 },
    prerequisiteIds: [],
  },
];
